<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'mohammed',
                'email' => 'mohammed@laravel.com',
                'email_verified_at' => '2026-02-17 06:07:41',
                'password' => '$2y$12$8El8ZM149qQdIbpiTXQCeec7vpKmbpqY7XzcQiJZGur6Oow9a06iK',
                'remember_token' => 'MOPBJeTOGoU7QEr82qHwV1sFbIQVzi3IRByHLvWl1sCo8pP9gtLtuKU0Vi1L',
                'created_at' => '2026-02-02 20:10:42',
                'updated_at' => '2026-03-17 21:15:09',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'user',
                'email' => 'user@laravel.com',
                'email_verified_at' => '2026-02-17 06:07:41',
                'password' => '$2y$12$I0HBgtPb2h54mTbOudNqqetaX/xMMUvAcW9P/Ubud2wswhLwwLZ2W',
                'remember_token' => 'R5wuzc0xlA',
                'created_at' => '2026-02-17 06:07:41',
                'updated_at' => '2026-02-17 06:07:41',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'user12',
                'email' => 'user12@laravel.com',
                'email_verified_at' => '2026-03-03 11:24:55',
                'password' => '$2y$12$W6FiJgY5Xb3n5CYoomSCdOd7QJi01XpQuSiucQ4XK/QKEjy6qjcVu',
                'remember_token' => NULL,
                'created_at' => '2026-03-03 10:51:48',
                'updated_at' => '2026-03-03 11:24:55',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'name' => 'user123',
                'email' => 'user123@laravel.com',
                'email_verified_at' => '2026-03-03 11:24:55',
                'password' => '$2y$12$qeGaFZp38q5ZpAwnic9Nqe70zbYKfMX7WqpOXeGBTpvqUTOQWeApm',
                'remember_token' => NULL,
                'created_at' => '2026-03-11 14:01:34',
                'updated_at' => '2026-03-11 14:01:34',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            4 => 
            array (
                'id' => 77,
                'name' => 'Diego Keeling',
                'email' => 'cali.kautzer@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => '443PSimblZ',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            5 => 
            array (
                'id' => 78,
                'name' => 'Marques Hilpert',
                'email' => 'jklein@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'lI5U62puFa',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            6 => 
            array (
                'id' => 79,
                'name' => 'Colby Bashirian MD',
                'email' => 'spurdy@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'FyXeOVGPAx',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            7 => 
            array (
                'id' => 80,
                'name' => 'Jovan Dare MD',
                'email' => 'udibbert@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => '9qWiox8luz',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            8 => 
            array (
                'id' => 81,
                'name' => 'Mr. Devin Little',
                'email' => 'emmerich.esmeralda@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'TgitIH5V9y',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            9 => 
            array (
                'id' => 82,
                'name' => 'Polly Watsica',
                'email' => 'clinton51@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'r78L2IH9tt',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            10 => 
            array (
                'id' => 83,
                'name' => 'Joshua Toy',
                'email' => 'ebert.kendra@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'Ey8cgQj3sm',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            11 => 
            array (
                'id' => 84,
                'name' => 'Hettie Mosciski',
                'email' => 'utoy@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'TVtKEyNXYF',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            12 => 
            array (
                'id' => 85,
                'name' => 'Callie Von PhD',
                'email' => 'roger.hodkiewicz@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'cj3QJq8MVP',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            13 => 
            array (
                'id' => 86,
                'name' => 'Mrs. Kirstin Denesik',
                'email' => 'giles18@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'Ki37fSbey7',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            14 => 
            array (
                'id' => 87,
                'name' => 'Wava Effertz',
                'email' => 'ron11@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'jjpWbuUBop',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            15 => 
            array (
                'id' => 88,
                'name' => 'Concepcion Watsica DDS',
                'email' => 'pschulist@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'QHJ49CiTLx',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            16 => 
            array (
                'id' => 89,
                'name' => 'Omari Raynor',
                'email' => 'ole.lowe@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'j9ACgkWM5o',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            17 => 
            array (
                'id' => 90,
                'name' => 'Miles Funk',
                'email' => 'apagac@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'pu9AOE3qpN',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            18 => 
            array (
                'id' => 91,
                'name' => 'Dr. Jeromy Hyatt',
                'email' => 'wrobel@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'gmLv0tqaCf',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            19 => 
            array (
                'id' => 92,
                'name' => 'Kenya Ullrich PhD',
                'email' => 'andres03@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'Sjmq3nrX1u',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            20 => 
            array (
                'id' => 93,
                'name' => 'German Carroll I',
                'email' => 'obauch@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'O5I0PL4H4H',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            21 => 
            array (
                'id' => 94,
                'name' => 'Manuela Hane',
                'email' => 'monica.schultz@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'UFRnnv1GAr',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            22 => 
            array (
                'id' => 95,
                'name' => 'Brooklyn Halvorson',
                'email' => 'nrutherford@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'QEjLsuSJRC',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            23 => 
            array (
                'id' => 96,
                'name' => 'Mr. Mallory Torphy',
                'email' => 'sherman18@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'B1CMVINqKI',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            24 => 
            array (
                'id' => 97,
                'name' => 'Justyn Smitham',
                'email' => 'antonina54@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'DZvsp2UVcU',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            25 => 
            array (
                'id' => 98,
                'name' => 'Marie Herzog',
                'email' => 'tara.denesik@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'BHOpd9pjFO',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            26 => 
            array (
                'id' => 99,
                'name' => 'Effie Schoen',
                'email' => 'xdonnelly@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'f54bRDGfcE',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            27 => 
            array (
                'id' => 100,
                'name' => 'Lyla Romaguera',
                'email' => 'stanton.maxine@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'G4f3R0wu2V',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            28 => 
            array (
                'id' => 101,
                'name' => 'Prof. Herta Torp',
                'email' => 'briana90@example.org',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'SMQB0WGIsl',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            29 => 
            array (
                'id' => 102,
                'name' => 'Dr. Seamus McCullough',
                'email' => 'okshlerin@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => '2griaRtr59',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            30 => 
            array (
                'id' => 103,
                'name' => 'Mrs. Gisselle Daugherty DVM',
                'email' => 'ihowe@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => '6InREQPmGl',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            31 => 
            array (
                'id' => 104,
                'name' => 'Dr. Sanford Mraz MD',
                'email' => 'elangworth@example.com',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'QF0U6oiSij',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            32 => 
            array (
                'id' => 105,
                'name' => 'Ransom Wolff',
                'email' => 'vandervort.gladyce@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'rRH6cwv5Bd',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
            33 => 
            array (
                'id' => 106,
                'name' => 'Dariana Leannon',
                'email' => 'alford22@example.net',
                'email_verified_at' => '2026-04-05 20:38:20',
                'password' => '$2y$12$x1J0bWgyi2eKjRTY.ZhAiOCh9U6qm8/AbFe/IBC2qMWXV1zI3Lh9C',
                'remember_token' => 'id3oG6jbIA',
                'created_at' => '2026-04-05 20:38:20',
                'updated_at' => '2026-04-05 20:38:20',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_confirmed_at' => NULL,
            ),
        ));
        
        
    }
}